
if (USE_VECLIB)
    if (APPLE)
        find_package(vecLib ${FIND_MODE})
        if (vecLib_FOUND)
            include_directories(${vecLib_INCLUDE_DIR})
            set(LAPACK_LIBRARIES ${vecLib_LINKER_LIBS})
            # set the found BLASLAPACK_IMPLEMENTATION (in case it was Auto)
            set(BLASLAPACK_IMPLEMENTATION "vecLib" CACHE STRING "${BLASLAPACK_IMPLEMENTATION_DOCSTRING}" FORCE)
            list(APPEND OpenMEEG_DEPENDENCIES vecLib)
        endif()
    else()
        message(WARNING "vecLib is only on Apple MAC OS")
    endif()
endif()
